# Generated by Django 3.2.5 on 2021-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dozi',
            name='since_join',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
