# Generated by Django 3.2.5 on 2021-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20211207_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('medicine_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Medicine Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description 1')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price')),
            ],
        ),
    ]
