# Generated by Django 3.2.5 on 2021-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='accepted_tarehe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
